apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowd-deployment
  namespace: production
  labels:
    service: crowd
    app: crowd

spec:
  replicas: 1
  selector:
    matchLabels:
      app: crowd
  template:
    metadata:
      labels:
        app: crowd
    spec:
      containers:
        - name: crowd
          image: dchevell/crowd:latest
          imagePullPolicy: Always
          env:
            - name: JVM_MINIMUM_MEMORY
              value: 1024m
            - name: JVM_MAXIMUM_MEMORY
              value: 1024m
          ports:
            - containerPort: 8095
          volumeMounts:
          - mountPath: "/var/atlassian/application-data/crowd"
            name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfsprodcrowd
