apiVersion: v1
kind: Service
metadata:
  name: crowd
  namespace: production
  labels:
    app: crowd
spec:
  type: LoadBalancer
  externalIPs:
    - 10.1.1.24
    - 10.1.1.25
  ports:
  - name: http
    port: 8095
    targetPort: 8095
    protocol: TCP
  selector:
    app: crowd