apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: production
  name: nfsprodcrowd
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.1.1.22
    path: "/root/nfs/crowd_prod"