apiVersion: v1
kind: Service
metadata:
  name: crowd
  namespace: test
  labels:
    app: crowd
spec:
  type: LoadBalancer
  externalIPs:
    - "10.250.201.248"
    - "10.250.201.248"
    - "10.250.204.157"
    - "10.250.218.215"
  ports:
  - name: http
    port: 8095
    targetPort: 8095
    protocol: TCP
  selector:
    app: crowd