apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bamboo
  namespace: test
  
  labels:
    service: bamboo
    app: bamboo
  env:
    log-driver: json-file
    log-opts: 
      max-size: "10m"
      max-file: "3"
spec:
  replicas: 1
  serviceName: bamboo-svc
  selector:
    matchLabels:
      app: bamboo
  template:
    metadata:
      labels:
        app: bamboo
      
    spec:
      containers:
      - name: bamboo
        image: atlassian/bamboo-server:6.8.1
        imagePullPolicy: Always
        env:
          - name: JVM_MINIMUM_MEMORY
            value: "1536m"
          - name: JVM_MAXIMUM_MEMORY
            value: "1536m"
          - name: PROXYNAME
            value: "bamboo.domain.xyz"
          - name: PROXYSCHEME
            value: "https"
          - name: PROXYSECURE
            value: "true"
        ports:
          - containerPort: 8085
        volumeMounts:
        - mountPath: "/var/atlassian/application-data/bamboo"
          name: bamboopv

      volumes:
      - name: bamboopv
---
apiVersion: v1
kind: Service
metadata:
  name: bamboo-svc
  namespace: test
  labels:
    app: bamboo
spec:
  type:
  externalIPs:
    - "10.250.201.248"
    - "10.250.201.248"
    - "10.250.204.157"
    - "10.250.218.215"
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: bamboo