---
- hosts: localhost
  tasks:
  - name: Clean up the directory
    file: path=/tmp/k8s/bitbucket state=absent

  - name: Create the tmp directory
    file: path=/tmp/k8s/bitbucket state=directory

  - name: Render files template to /tmp/k8s/bitbucket
    template: src={{ item }} dest=/tmp/k8s/bitbucket/{{ item | basename }}
    with_fileglob: "{{playbook_dir}}/*.yml"
    # You can add extra conditional stuff here, example
    #when cluster_name in ["cluster1"]


  ###############################################################

  - name: Deploy bitbucket objects to cluster
    command: kubectl -n {{namespace}} apply -f /tmp/k8s/bitbucket

    # You can add extra conditional stuff here, example
    #when cluster_name in ["cluster1"]

  #- name: Clean up the directory
  #  file: path=/tmp/k8s/bitbucket state=absent
  #  tags:
  #  - cleanup