apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{namespace}}
  name: {{bitbucketvolumename}}
spec:
  capacity:
    storage: {{storagesize}}
  accessModes:
  - ReadWriteMany
  nfs:
    server: {{nfsserverip}}
    path: {{nfspath}}