apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket-deployment
  namespace: test
  labels:
    service: bitbucket
    app: bitbucket

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitbucket
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      containers:
        - name: bitbucket
          image: atlassian/bitbucket-server:latest
          imagePullPolicy: Always
          env:
            - name: JVM_MINIMUM_MEMORY
              value: "1536m"
            - name: JVM_MAXIMUM_MEMORY
              value: "1536m"
            - name: SERVER_PROXY_PORT
              value: "443"
            - name: SERVER_PROXY_NAME
              value: "bitbucket.domain.xyz"
            - name: SERVER_SCHEME
              value: "https"
            - name: SERVER_SECURE
              value: "true"
          ports:
            - containerPort: 7990
          volumeMounts:
          - mountPath: "/var/atlassian/application-data/bitbucket"
            name: bitbucketpv
      volumes:
      - name: bitbucketpv
