apiVersion: v1
kind: Service
metadata:
  name: bitbucket-svc
  namespace: test
  labels:
    app: bitbucket
spec:
  type: LoadBalancer
  externalIPs:
    - "10.250.201.248"
    - "10.250.201.248"
    - "10.250.204.157"
    - "10.250.218.215"
  ports:
  - name: http
    port: 7990
    targetPort: 7990
    protocol: TCP
  selector:
    app: bitbucket