apiVersion: v1
kind: Service
metadata:
  name: {{bitbucketk8sservicename}}
  namespace: {{namespace}}
  labels:
    app: {{appname}}
spec:
  type: LoadBalancer
  externalIPs:
    - {{nodeip1}}
    - {{nodeip2}}
  ports:
  - name: http
    port: 7990
    targetPort: 7990
    protocol: TCP
  selector:
    app: {{appname}}