apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: postgres-atlas
  labels:
    service: postgres-atlas
    app: test


spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-atlas
  template:
    metadata:
      labels:
        app: postgres-atlas
    spec:
      containers:
        - name: postgres-atlas
          image: mbern/postgres-atlas-all:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data/"
              name: postgresatlaspv
      volumes:
        - name: postgresatlaspv
